const translations = {
  en: {
    "common.tagline": "TravelKo",
    "nav.home": "Home",
    "nav.explore": "Explore",
    "nav.lang": "한국어",

    "app.title": "Discover Korea",
    "app.subtitle": "Travel spots recommended by the community",
    "app.searchPh": "Search places...",
    "app.catAll": "All",
    "app.catFood": "Food",
    "app.catAttraction": "Attractions",
    "app.catCafe": "Cafe",
    "app.catNature": "Nature",
    "app.catShopping": "Shopping",
    "app.catNightlife": "Nightlife",
    "app.regionAll": "All Regions",
    "app.regionSeoul": "Seoul",
    "app.regionBusan": "Busan",
    "app.regionJeju": "Jeju",
    "app.regionIncheon": "Incheon",
    "app.regionGyeonggi": "Gyeonggi",
    "app.regionOther": "Other",
    "app.featured": "Featured",
    "app.rating": "Rating",
    "app.views": "Views",
    "app.noResults": "No spots found. Try a different filter.",
    "app.loading": "Loading spots...",
    "app.loadMore": "Load More",
    "app.openNaver": "Open in Naver Map",
    "app.openGoogle": "Open in Google Map",
    "app.mapNaver": "Naver Map",
    "app.mapGoogle": "Google Map",
    "app.shareSpot": "Share a Spot",
    "app.submitTitle": "Share a Travel Spot",
    "app.submitNotice": "Your submission will appear after admin review.",
    "app.placeLabel": "Place Name",
    "app.placePh": "e.g. Gyeongbokgung Palace",
    "app.categoryLabel": "Category",
    "app.descLabel": "Your Review",
    "app.descPh": "Share your experience...",
    "app.addressLabel": "Address",
    "app.addressPh": "Search address...",
    "app.searchBtn": "Search",
    "app.instagramLabel": "Instagram Tags",
    "app.instagramPh": "@username or #hashtag",
    "app.authorLabel": "Your Name",
    "app.authorPh": "Your name",
    "app.cancelBtn": "Cancel",
    "app.submitBtn": "Submit",
    "app.submitted": "Thank you! Your spot will appear after admin review.",
    "app.submitError": "Failed to submit. Please try again.",
    "app.mapError": "Map could not be loaded.",

    "footer.text": "© 2026 TravelKo by KoInfo. Discover Korea together.",
  },

  ko: {
    "common.tagline": "트래블코",
    "nav.home": "홈",
    "nav.explore": "탐색",
    "nav.lang": "English",

    "app.title": "한국을 발견하세요",
    "app.subtitle": "커뮤니티가 추천하는 여행 명소",
    "app.searchPh": "장소 검색...",
    "app.catAll": "전체",
    "app.catFood": "맛집",
    "app.catAttraction": "관광지",
    "app.catCafe": "카페",
    "app.catNature": "자연",
    "app.catShopping": "쇼핑",
    "app.catNightlife": "나이트라이프",
    "app.regionAll": "전체 지역",
    "app.regionSeoul": "서울",
    "app.regionBusan": "부산",
    "app.regionJeju": "제주",
    "app.regionIncheon": "인천",
    "app.regionGyeonggi": "경기",
    "app.regionOther": "기타",
    "app.featured": "추천",
    "app.rating": "평점",
    "app.views": "조회",
    "app.noResults": "검색 결과가 없습니다. 다른 필터를 시도해 보세요.",
    "app.loading": "불러오는 중...",
    "app.loadMore": "더 보기",
    "app.openNaver": "네이버 지도에서 열기",
    "app.openGoogle": "구글 지도에서 열기",
    "app.mapNaver": "네이버 지도",
    "app.mapGoogle": "구글 지도",
    "app.shareSpot": "여행지 공유",
    "app.submitTitle": "여행지 공유하기",
    "app.submitNotice": "관리자 승인 후 게시됩니다.",
    "app.placeLabel": "장소 이름",
    "app.placePh": "예: 경복궁",
    "app.categoryLabel": "카테고리",
    "app.descLabel": "리뷰",
    "app.descPh": "경험을 공유하세요...",
    "app.addressLabel": "주소",
    "app.addressPh": "주소 검색...",
    "app.searchBtn": "검색",
    "app.instagramLabel": "인스타그램 태그",
    "app.instagramPh": "@계정 또는 #해시태그",
    "app.authorLabel": "작성자",
    "app.authorPh": "이름",
    "app.cancelBtn": "취소",
    "app.submitBtn": "제출",
    "app.submitted": "감사합니다! 관리자 승인 후 게시됩니다.",
    "app.submitError": "제출에 실패했습니다. 다시 시도해 주세요.",
    "app.mapError": "지도를 불러올 수 없습니다.",

    "footer.text": "© 2026 TravelKo by KoInfo. 함께 한국을 발견하세요.",
  },

  id: {
    "common.tagline": "TravelKo",
    "nav.home": "Beranda",
    "nav.explore": "Jelajahi",
    "nav.lang": "한국어",

    "app.title": "Temukan Korea",
    "app.subtitle": "Tempat wisata rekomendasi komunitas",
    "app.searchPh": "Cari tempat...",
    "app.catAll": "Semua",
    "app.catFood": "Kuliner",
    "app.catAttraction": "Wisata",
    "app.catCafe": "Kafe",
    "app.catNature": "Alam",
    "app.catShopping": "Belanja",
    "app.catNightlife": "Hiburan Malam",
    "app.regionAll": "Semua Wilayah",
    "app.regionSeoul": "Seoul",
    "app.regionBusan": "Busan",
    "app.regionJeju": "Jeju",
    "app.regionIncheon": "Incheon",
    "app.regionGyeonggi": "Gyeonggi",
    "app.regionOther": "Lainnya",
    "app.featured": "Pilihan",
    "app.rating": "Rating",
    "app.views": "Dilihat",
    "app.noResults": "Tidak ada tempat ditemukan. Coba filter lain.",
    "app.loading": "Memuat...",
    "app.loadMore": "Muat Lagi",
    "app.openNaver": "Buka di Naver Map",
    "app.openGoogle": "Buka di Google Map",
    "app.mapNaver": "Naver Map",
    "app.mapGoogle": "Google Map",
    "app.shareSpot": "Bagikan Tempat",
    "app.submitTitle": "Bagikan Tempat Wisata",
    "app.submitNotice": "Akan tampil setelah disetujui admin.",
    "app.placeLabel": "Nama Tempat",
    "app.placePh": "contoh: Istana Gyeongbokgung",
    "app.categoryLabel": "Kategori",
    "app.descLabel": "Ulasan Anda",
    "app.descPh": "Bagikan pengalaman Anda...",
    "app.addressLabel": "Alamat",
    "app.addressPh": "Cari alamat...",
    "app.searchBtn": "Cari",
    "app.instagramLabel": "Tag Instagram",
    "app.instagramPh": "@username atau #hashtag",
    "app.authorLabel": "Nama Anda",
    "app.authorPh": "Nama Anda",
    "app.cancelBtn": "Batal",
    "app.submitBtn": "Kirim",
    "app.submitted": "Terima kasih! Tempat Anda akan tampil setelah ditinjau admin.",
    "app.submitError": "Gagal mengirim. Silakan coba lagi.",
    "app.mapError": "Peta tidak dapat dimuat.",

    "footer.text": "© 2026 TravelKo by KoInfo. Temukan Korea bersama.",
  },

  mn: {
    "common.tagline": "TravelKo",
    "nav.home": "Нүүр",
    "nav.explore": "Нээх",
    "nav.lang": "한국어",

    "app.title": "Солонгосыг нээгээрэй",
    "app.subtitle": "Коммунитигээс санал болгосон аялалын газрууд",
    "app.searchPh": "Газар хайх...",
    "app.catAll": "Бүгд",
    "app.catFood": "Хоол",
    "app.catAttraction": "Үзмэр газар",
    "app.catCafe": "Кафе",
    "app.catNature": "Байгаль",
    "app.catShopping": "Дэлгүүр",
    "app.catNightlife": "Шөнийн амьдрал",
    "app.regionAll": "Бүх бүс",
    "app.regionSeoul": "Сөүл",
    "app.regionBusan": "Пусан",
    "app.regionJeju": "Жэжу",
    "app.regionIncheon": "Инчон",
    "app.regionGyeonggi": "Кёнги",
    "app.regionOther": "Бусад",
    "app.featured": "Онцлох",
    "app.rating": "Үнэлгээ",
    "app.views": "Үзсэн",
    "app.noResults": "Газар олдсонгүй. Өөр шүүлтүүр туршаарай.",
    "app.loading": "Ачаалж байна...",
    "app.loadMore": "Дэлгэрэнгүй",
    "app.openNaver": "Naver Map-д нээх",
    "app.openGoogle": "Google Map-д нээх",
    "app.mapNaver": "Naver Map",
    "app.mapGoogle": "Google Map",
    "app.shareSpot": "Газар хуваалцах",
    "app.submitTitle": "Аялалын газар хуваалцах",
    "app.submitNotice": "Админ зөвшөөрсний дараа нийтлэгдэнэ.",
    "app.placeLabel": "Газрын нэр",
    "app.placePh": "жишээ: Кёнбоккүн ордон",
    "app.categoryLabel": "Ангилал",
    "app.descLabel": "Тойм",
    "app.descPh": "Туршлагаа хуваалцаарай...",
    "app.addressLabel": "Хаяг",
    "app.addressPh": "Хаяг хайх...",
    "app.searchBtn": "Хайх",
    "app.instagramLabel": "Instagram таг",
    "app.instagramPh": "@хэрэглэгч эсвэл #hashtag",
    "app.authorLabel": "Таны нэр",
    "app.authorPh": "Нэр",
    "app.cancelBtn": "Цуцлах",
    "app.submitBtn": "Илгээх",
    "app.submitted": "Баярлалаа! Админ зөвшөөрсний дараа харагдана.",
    "app.submitError": "Илгээхэд алдаа гарлаа. Дахин оролдоно уу.",
    "app.mapError": "Газрын зургийг ачаалж чадсангүй.",

    "footer.text": "© 2026 TravelKo by KoInfo. Солонгосыг хамтдаа нээцгээе.",
  },

  ms: {
    "common.tagline": "TravelKo",
    "nav.home": "Laman Utama",
    "nav.explore": "Terokai",
    "nav.lang": "한국어",

    "app.title": "Temui Korea",
    "app.subtitle": "Tempat pelancongan cadangan komuniti",
    "app.searchPh": "Cari tempat...",
    "app.catAll": "Semua",
    "app.catFood": "Makanan",
    "app.catAttraction": "Tarikan",
    "app.catCafe": "Kafe",
    "app.catNature": "Alam Semula Jadi",
    "app.catShopping": "Beli-belah",
    "app.catNightlife": "Kehidupan Malam",
    "app.regionAll": "Semua Wilayah",
    "app.regionSeoul": "Seoul",
    "app.regionBusan": "Busan",
    "app.regionJeju": "Jeju",
    "app.regionIncheon": "Incheon",
    "app.regionGyeonggi": "Gyeonggi",
    "app.regionOther": "Lain-lain",
    "app.featured": "Pilihan",
    "app.rating": "Penilaian",
    "app.views": "Tontonan",
    "app.noResults": "Tiada tempat ditemui. Cuba penapis lain.",
    "app.loading": "Memuatkan...",
    "app.loadMore": "Muat Lagi",
    "app.openNaver": "Buka di Naver Map",
    "app.openGoogle": "Buka di Google Map",
    "app.mapNaver": "Naver Map",
    "app.mapGoogle": "Google Map",
    "app.shareSpot": "Kongsi Tempat",
    "app.submitTitle": "Kongsi Tempat Pelancongan",
    "app.submitNotice": "Akan dipaparkan selepas semakan admin.",
    "app.placeLabel": "Nama Tempat",
    "app.placePh": "cth: Istana Gyeongbokgung",
    "app.categoryLabel": "Kategori",
    "app.descLabel": "Ulasan Anda",
    "app.descPh": "Kongsi pengalaman anda...",
    "app.addressLabel": "Alamat",
    "app.addressPh": "Cari alamat...",
    "app.searchBtn": "Cari",
    "app.instagramLabel": "Tag Instagram",
    "app.instagramPh": "@pengguna atau #hashtag",
    "app.authorLabel": "Nama Anda",
    "app.authorPh": "Nama anda",
    "app.cancelBtn": "Batal",
    "app.submitBtn": "Hantar",
    "app.submitted": "Terima kasih! Tempat anda akan dipaparkan selepas semakan admin.",
    "app.submitError": "Gagal menghantar. Sila cuba lagi.",
    "app.mapError": "Peta tidak dapat dimuatkan.",

    "footer.text": "© 2026 TravelKo by KoInfo. Temui Korea bersama.",
  },

  vi: {
    "common.tagline": "TravelKo",
    "nav.home": "Trang ch\u1ee7",
    "nav.explore": "Kh\u00e1m ph\u00e1",
    "nav.lang": "\ud55c\uad6d\uc5b4",

    "app.title": "Kh\u00e1m ph\u00e1 H\u00e0n Qu\u1ed1c",
    "app.subtitle": "\u0110i\u1ec3m du l\u1ecbch \u0111\u01b0\u1ee3c c\u1ed9ng \u0111\u1ed3ng \u0111\u1ec1 xu\u1ea5t",
    "app.searchPh": "T\u00ecm \u0111\u1ecba \u0111i\u1ec3m...",
    "app.catAll": "T\u1ea5t c\u1ea3",
    "app.catFood": "\u1ea8m th\u1ef1c",
    "app.catAttraction": "\u0110i\u1ec3m tham quan",
    "app.catCafe": "C\u00e0 ph\u00ea",
    "app.catNature": "Thi\u00ean nhi\u00ean",
    "app.catShopping": "Mua s\u1eafm",
    "app.catNightlife": "Cu\u1ed9c s\u1ed1ng v\u1ec1 \u0111\u00eam",
    "app.regionAll": "T\u1ea5t c\u1ea3 khu v\u1ef1c",
    "app.regionSeoul": "Seoul",
    "app.regionBusan": "Busan",
    "app.regionJeju": "Jeju",
    "app.regionIncheon": "Incheon",
    "app.regionGyeonggi": "Gyeonggi",
    "app.regionOther": "Kh\u00e1c",
    "app.featured": "N\u1ed5i b\u1eadt",
    "app.rating": "\u0110\u00e1nh gi\u00e1",
    "app.views": "L\u01b0\u1ee3t xem",
    "app.noResults": "Kh\u00f4ng t\u00ecm th\u1ea5y \u0111\u1ecba \u0111i\u1ec3m. Th\u1eed b\u1ed9 l\u1ecdc kh\u00e1c.",
    "app.loading": "\u0110ang t\u1ea3i...",
    "app.loadMore": "Xem th\u00eam",
    "app.openNaver": "M\u1edf trong Naver Map",
    "app.openGoogle": "M\u1edf trong Google Map",
    "app.mapNaver": "Naver Map",
    "app.mapGoogle": "Google Map",
    "app.shareSpot": "Chia s\u1ebb \u0111\u1ecba \u0111i\u1ec3m",
    "app.submitTitle": "Chia s\u1ebb \u0111\u1ecba \u0111i\u1ec3m du l\u1ecbch",
    "app.submitNotice": "S\u1ebd hi\u1ec3n th\u1ecb sau khi qu\u1ea3n tr\u1ecb vi\u00ean duy\u1ec7t.",
    "app.placeLabel": "T\u00ean \u0111\u1ecba \u0111i\u1ec3m",
    "app.placePh": "v\u00ed d\u1ee5: C\u00f4ng Gyeongbokgung",
    "app.categoryLabel": "Danh m\u1ee5c",
    "app.descLabel": "\u0110\u00e1nh gi\u00e1 c\u1ee7a b\u1ea1n",
    "app.descPh": "Chia s\u1ebb tr\u1ea3i nghi\u1ec7m c\u1ee7a b\u1ea1n...",
    "app.addressLabel": "\u0110\u1ecba ch\u1ec9",
    "app.addressPh": "T\u00ecm \u0111\u1ecba ch\u1ec9...",
    "app.searchBtn": "T\u00ecm",
    "app.instagramLabel": "Tag Instagram",
    "app.instagramPh": "@t\u00e0i kho\u1ea3n ho\u1eb7c #hashtag",
    "app.authorLabel": "T\u00ean c\u1ee7a b\u1ea1n",
    "app.authorPh": "T\u00ean c\u1ee7a b\u1ea1n",
    "app.cancelBtn": "H\u1ee7y",
    "app.submitBtn": "G\u1eedi",
    "app.submitted": "C\u1ea3m \u01a1n! \u0110\u1ecba \u0111i\u1ec3m s\u1ebd hi\u1ec3n th\u1ecb sau khi \u0111\u01b0\u1ee3c duy\u1ec7t.",
    "app.submitError": "G\u1eedi th\u1ea5t b\u1ea1i. Vui l\u00f2ng th\u1eed l\u1ea1i.",
    "app.mapError": "Kh\u00f4ng th\u1ec3 t\u1ea3i b\u1ea3n \u0111\u1ed3.",

    "footer.text": "\u00a9 2026 TravelKo by KoInfo. C\u00f9ng kh\u00e1m ph\u00e1 H\u00e0n Qu\u1ed1c.",
  },
};
